force-app/main/default/objects/Offset__c/Offset__c.object-meta.xml
<CustomObject>
    <label>Offset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offsets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Offset__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Offset__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Offsets</relationshipLabel>
    <relationshipName>Offsets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Offset__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <label>Provider</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offset__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tree Planting</fullName>
            </value>
            <value>
                <fullName>Carbon Credit</fullName>
            </value>
            <value>
                <fullName>Renewable Energy</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OffsetController.cls
public with sharing class OffsetController {
    public Offset__c offset { get; set; }
    public Id projectId { get; set; }

    public OffsetController() {
        Id offsetId = ApexPages.currentPage().getParameters().get('id');
        offset = [SELECT Id, Name, Amount__c, Type__c, Provider__c, Date__c, Project__c
                  FROM Offset__c
                  WHERE Id = :offsetId];
        projectId = offset.Project__c;
    }

    public PageReference saveOffset() {
        update offset;
        return new PageReference('/apex/ProjectDetail?id=' + projectId);
    }
    public PageReference cancel() {
    return new PageReference('/apex/ProjectDetail?id=' + projectId);
}
}