force-app/main/default/objects/Emission__c/Emission__c.object-meta.xml
<CustomObject>
    <label>Emission</label>
    <nameField>
        <displayFormat>EMI-{000}</displayFormat>
        <label>Emission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Emission__c/fields/Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type__c</fullName>
    <label>Activity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Waste</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Emission__c/fields/Actual_Emission__c.field-meta.xml
<CustomField>
    <fullName>Actual_Emission__c</fullName>
    <label>Actual Emission</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Emission__c/fields/Estimated_Emission__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Emission__c</fullName>
    <label>Estimated Emission</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Emission__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Emissions</relationshipLabel>
    <relationshipName>Emissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Emission__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Emission__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmissionController.cls
public with sharing class EmissionController {
    public Emission__c emission { get; set; }
    public Id projectId { get; set; }

    public EmissionController() {
        Id emissionId = ApexPages.currentPage().getParameters().get('id');
        emission = [SELECT Id, Name, Activity_Type__c, Quantity__c, Unit__c,
                           Estimated_Emission__c, Actual_Emission__c, Date__c, Project__c
                    FROM Emission__c
                    WHERE Id = :emissionId];
        projectId = emission.Project__c;
    }

    public PageReference saveEmission() {
        update emission;
        return new PageReference('/apex/ProjectDetail?id=' + projectId);
    }
    public PageReference cancel() {
    return new PageReference('/apex/ProjectDetail?id=' + projectId);
}
}